//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARealShopEntities : DbContext
    {
        public ARealShopEntities()
            : base("name=ARealShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllViews> AllViews { get; set; }
        public virtual DbSet<AllViewsColumn> AllViewsColumn { get; set; }
        public virtual DbSet<ApkUrl> ApkUrl { get; set; }
        public virtual DbSet<CategoryTable> CategoryTable { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<DetailURL> DetailURL { get; set; }
        public virtual DbSet<DriverLocation> DriverLocation { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductColor> ProductColor { get; set; }
        public virtual DbSet<ProductImage> ProductImage { get; set; }
        public virtual DbSet<ProductPayment> ProductPayment { get; set; }
        public virtual DbSet<ProductRating> ProductRating { get; set; }
        public virtual DbSet<PurchaseStatus> PurchaseStatus { get; set; }
        public virtual DbSet<Reply> Reply { get; set; }
        public virtual DbSet<ShopCart> ShopCart { get; set; }
        public virtual DbSet<ShopCartList> ShopCartList { get; set; }
    }
}
