//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverLocation
    {
        public long Id { get; set; }
        public string ShopId { get; set; }
        public string DriverId { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
    
        public virtual ShopCart ShopCart { get; set; }
    }
}
