//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.ShopCart = new HashSet<ShopCart>();
            this.ProductRating = new HashSet<ProductRating>();
            this.Reply = new HashSet<Reply>();
        }
    
        public string Account { get; set; }
        public string Password { get; set; }
        public string Addr { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public System.DateTime Birth { get; set; }
        public string Role { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<byte> Job { get; set; }
        public Nullable<byte> Style { get; set; }
        public Nullable<byte> Money { get; set; }
    
        public virtual ICollection<ShopCart> ShopCart { get; set; }
        public virtual ICollection<ProductRating> ProductRating { get; set; }
        public virtual ICollection<Reply> Reply { get; set; }
    }
}
