//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CategoryTable = new HashSet<CategoryTable>();
            this.ProductImage = new HashSet<ProductImage>();
            this.ShopCartList = new HashSet<ShopCartList>();
            this.ProductColor = new HashSet<ProductColor>();
            this.ProductRating = new HashSet<ProductRating>();
            this.Reply = new HashSet<Reply>();
        }
    
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductSpec { get; set; }
        public int ProductPrice { get; set; }
        public string Sid { get; set; }
        public string ProductMemo1 { get; set; }
        public string ProductMemo2 { get; set; }
        public string ProductMemo3 { get; set; }
        public string ProductImgUrl1 { get; set; }
        public string ProductImgUrl2 { get; set; }
        public string ProductImgUrl3 { get; set; }
        public string ProductImgUrl4 { get; set; }
        public string ProductImgUrl5 { get; set; }
        public int ProductCost { get; set; }
        public System.DateTime Time { get; set; }
        public bool PushHot { get; set; }
        public int Quantity { get; set; }
        public bool OnShelf { get; set; }
        public Nullable<int> OrgPrice { get; set; }
    
        public virtual ICollection<CategoryTable> CategoryTable { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<ProductImage> ProductImage { get; set; }
        public virtual ICollection<ShopCartList> ShopCartList { get; set; }
        public virtual ICollection<ProductColor> ProductColor { get; set; }
        public virtual ICollection<ProductRating> ProductRating { get; set; }
        public virtual ICollection<Reply> Reply { get; set; }
    }
}
