//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public Reply()
        {
            this.Reply1 = new HashSet<Reply>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime Time { get; set; }
        public string Account { get; set; }
        public Nullable<int> RId { get; set; }
        public string ProductId { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<Reply> Reply1 { get; set; }
        public virtual Reply Reply2 { get; set; }
    }
}
